"""Generate packaging/version_info.txt for the Windows VERSIONINFO resource.

Generated rather than committed so the file properties of Magoo.exe can
never drift from magoo.__version__. Run by build.ps1 before PyInstaller.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from magoo import __version__  # noqa: E402

OUT = Path(__file__).resolve().parent / "version_info.txt"

COMPANY = "Magoo"
PRODUCT = "Magoo"
DESCRIPTION = "EVE Online industry planner"
COPYRIGHT = "MIT licensed. Not affiliated with CCP hf."

# VERSIONINFO wants a 4-tuple; __version__ is three components.
parts = tuple(int(p) for p in __version__.split(".")) + (0,)
quad = parts[:4]

OUT.write_text(
    f"""# Generated by packaging/make_version_info.py — do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={quad},
    prodvers={quad},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{COMPANY}'),
         StringStruct('FileDescription', '{DESCRIPTION}'),
         StringStruct('FileVersion', '{__version__}'),
         StringStruct('InternalName', 'Magoo'),
         StringStruct('LegalCopyright', '{COPYRIGHT}'),
         StringStruct('OriginalFilename', 'Magoo.exe'),
         StringStruct('ProductName', '{PRODUCT}'),
         StringStruct('ProductVersion', '{__version__}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""",
    encoding="utf-8",
)
print(f"wrote {OUT} for v{__version__}")
